### ISSUE TITLE
Communications Channel

### ISSUE THREAD

**Issue by Omeryl** [asbjornenge/refugeeroute#8]
Although I'm personally a big fan of IRC, there are multiple means you can use to communicate, and my favorite more user friendly ones include:
- Slack, Free albeit with a 10k message limit and no user limit (limit is really, really high, something like 300k or so iirc) (older messages are eradicated from the backlog and search). Has great mobile apps, desktop apps, and web app. 
- Mattermost, Free/Open Source. A Slack clone, but entirely self hosted. Aims to be Slack and more, no user or message limit (besides, of course, what you can handle for storage). No decent native mobile apps yet (has a mobile site to display to mobile users), just hit 1.0.

I will note that, if you're wanting to be inclusive of everybody to help regardless of location, would it be possible to keep the language in English for communications/app/site/GH Issues?

**Comment by Omeryl** [comment]
That said, these communication channels would be temporary until we have a website/application/etc where we should be able to move all communications to, to keep things centralized and not have duplicate features for developers and refugees?

**Comment by asbjornenge** [comment]
@Omeryl regarding English for comm. I totally agree. English should be the default lang for the project overall I think. I'll switch the README's soon (waiting for response from Norwegian refugee agencies before I switch).

Regarding dev comm. I guess Slack is a good enough option since it should be temporary anyway? I'll post back once I've made a slack group :smile: :+1:

**Comment by Omeryl** [comment]
@asbjornenge For my work's community, we use Slack. We set up [slackin](https://github.com/rauchg/slackin), a way to automatically invite people and to have a SVG user count for our GitHub README.

Example: https://modx.org/
SVG in README: https://github.com/modxcms/revolution/blob/2.x/README.md

**Comment by asbjornenge** [comment]
@Omeryl I ended up going with gitter.im - a bit easier to set up and since it's temporary anyway I'll go with that for now. There is already a link in the README pointing here: https://gitter.im/asbjornenge/refugeeroute Let me know if you have trouble joining us :smile:
